Recipe App: RoR group project
algerina/recipe-app pull request #26
Opened 2022-05-19 21:04 UTC by Bondok6

# Hello there 🙋‍♂️,

### Thanks for taking the time to review our project.
<hr>

## What was done in this PR by @eduardosancho & @Bondok6 🧾
 
- [ ] Use Ruby gems as a software package system.
- [ ]  Install Ruby on Rails framework.
- [ ]  Understand Rails RESTful design and router.
- [ ]  Use controllers to handle requests and render empty views.
- [ ]  Understand Rails naming conventions.
- [ ]  Use params from browser requests in a safe way.
- [ ]  Use preprocessed HTML file with embedded Ruby code.
- [ ]  Use layouts and templates for shared content.
- [ ]  Use database migration files to maintain database schema.
- [ ]  Use validations for models.
- [ ]  Secure app from n+1 problems.
- [ ]  Understand what ORM is.
- [ ]  Write SQL queries with ActiveRecord.
- [ ]  Set up associations between models.
- [ ]  Build a web app that requires the user to log in.
- [ ]  Describe the difference between authorization and authentication.
- [ ]  Use Devise gem for authentication.
- [ ]  Understand how sessions and cookies can support authentication.
- [ ]  Limit access to web app resources based on authorization rules.

To Run the test
```bash
 bundle exec rspec spec/views/
```

2022-05-19 21:36 UTC, GzimAsani requested changes
### Hi @Bondok6 and @algerina 
 
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Awesome job, I really liked your project :wave: 
 
 ## Required Changes 
- [ ]  _Check inline comments :arrow_double_down:_ 

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-19 21:36 UTC, GzimAsani commented on app/views/public_recipes/index.html.erb
> +</div>
- [ ] Here the user should be able to click the public recipe which will then lead to  recipe details

2022-05-19 21:36 UTC, GzimAsani commented on app/views/recipes/index.html.erb
> +  <%end%>
- [ ] When another user checks for another public recipe it does not match the given wireframe ,kindly fix it, it looks kind of broken on the right side
![Screenshot from 2022-05-19 23-28-16](https://user-images.githubusercontent.com/62705947/169407828-ebf57f49-5165-498d-9e64-b39d939419aa.png)

2022-05-19 21:36 UTC, GzimAsani commented on app/views/shared/_navbar.html.erb
> +            <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link btn btn-outline-danger' %>
- [ ] When I click logout, it logs out but it does not update the page immediately, it lets the user know only after he clicked something else. KIndly improve this for a better user experience

2022-05-19 21:36 UTC, GzimAsani commented on spec/rails_helper.rb
> +require 'spec_helper'
- [ ] Please add more tests for both unit and integration which cover more in-depth your app

2022-05-20 00:51 UTC, EricMbouwe approved these changes
Hi @Bondok6 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-20 14:41 UTC, merged